### PR TITLE
update regex replaceFunction to match String.prototype.replace

### PR DESCRIPTION
**Pull request by mehtaphysical**
resolves https://github.com/eugeneware/replacestream/issues/15

### CODE REVIEW

**Comment by eugeneware** [comment]
LGTM! :clap:

**Comment by mehtaphysical** [comment]
@eugeneware what's the procedure for merging this?

**Comment by eugeneware** [comment]
I think what we'll do in the future is get at least one contributor to OK/LGTM the PR, and then either you or I (who have npm publish permission) can do the publish.

I'll merge and publish this one now to save time.

Thanks for the PR BTW!

**Comment by eugeneware** [comment]
I've published this as 2.0.0 as it's an API change that might break code.

**Pull request merged**
